/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BookshelfBookshelf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BookshelfBookshelf'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.Bookshelf = factory(root.BookBlogApi.ApiClient, root.BookBlogApi.BookshelfBookshelf);
  }
}(this, function(ApiClient, BookshelfBookshelf) {
  'use strict';

  /**
   * The Bookshelf model module.
   * @module model/Bookshelf
   * @version 0.0.5
   */

  /**
   * Constructs a new <code>Bookshelf</code>.
   * @alias module:model/Bookshelf
   * @class
   * @param num {Number} 
   * @param bookshelf {Array.<module:model/BookshelfBookshelf>} 
   */
  var exports = function(num, bookshelf) {
    this.num = num;
    this.bookshelf = bookshelf;
  };

  /**
   * Constructs a <code>Bookshelf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bookshelf} obj Optional instance to populate.
   * @return {module:model/Bookshelf} The populated <code>Bookshelf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('num'))
        obj.num = ApiClient.convertToType(data['num'], 'Number');
      if (data.hasOwnProperty('bookshelf'))
        obj.bookshelf = ApiClient.convertToType(data['bookshelf'], [BookshelfBookshelf]);
    }
    return obj;
  }

  /**
   * @member {Number} num
   */
  exports.prototype.num = undefined;

  /**
   * @member {Array.<module:model/BookshelfBookshelf>} bookshelf
   */
  exports.prototype.bookshelf = undefined;


  return exports;

}));
