/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 0.0.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.BookshelfBookshelf = factory(root.BookBlogApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BookshelfBookshelf model module.
   * @module model/BookshelfBookshelf
   * @version 0.0.4
   */

  /**
   * Constructs a new <code>BookshelfBookshelf</code>.
   * @alias module:model/BookshelfBookshelf
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BookshelfBookshelf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BookshelfBookshelf} obj Optional instance to populate.
   * @return {module:model/BookshelfBookshelf} The populated <code>BookshelfBookshelf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bookName'))
        obj.bookName = ApiClient.convertToType(data['bookName'], 'String');
      if (data.hasOwnProperty('bookId'))
        obj.bookId = ApiClient.convertToType(data['bookId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} bookName
   */
  exports.prototype.bookName = undefined;

  /**
   * @member {Number} bookId
   */
  exports.prototype.bookId = undefined;

  return exports;

}));
