/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BookshelfsBookshelfs'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BookshelfsBookshelfs'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.Bookshelfs = factory(root.BookBlogApi.ApiClient, root.BookBlogApi.BookshelfsBookshelfs);
  }
}(this, function(ApiClient, BookshelfsBookshelfs) {
  'use strict';

  /**
   * The Bookshelfs model module.
   * @module model/Bookshelfs
   * @version 0.0.5
   */

  /**
   * Constructs a new <code>Bookshelfs</code>.
   * @alias module:model/Bookshelfs
   * @class
   * @param num {Number} 
   * @param bookshelfs {Array.<module:model/BookshelfsBookshelfs>} 
   */
  var exports = function(num, bookshelfs) {
    this.num = num;
    this.bookshelfs = bookshelfs;
  };

  /**
   * Constructs a <code>Bookshelfs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bookshelfs} obj Optional instance to populate.
   * @return {module:model/Bookshelfs} The populated <code>Bookshelfs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('num'))
        obj.num = ApiClient.convertToType(data['num'], 'Number');
      if (data.hasOwnProperty('bookshelfs'))
        obj.bookshelfs = ApiClient.convertToType(data['bookshelfs'], [BookshelfsBookshelfs]);
    }
    return obj;
  }

  /**
   * @member {Number} num
   */
  exports.prototype.num = undefined;

  /**
   * @member {Array.<module:model/BookshelfsBookshelfs>} bookshelfs
   */
  exports.prototype.bookshelfs = undefined;


  return exports;

}));
