/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 0.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BookshelfInner'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BookshelfInner'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.Bookshelf = factory(root.BookBlogApi.ApiClient, root.BookBlogApi.BookshelfInner);
  }
}(this, function(ApiClient, BookshelfInner) {
  'use strict';

  /**
   * The Bookshelf model module.
   * @module model/Bookshelf
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>Bookshelf</code>.
   * @alias module:model/Bookshelf
   * @class
   * @extends Array
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Bookshelf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bookshelf} obj Optional instance to populate.
   * @return {module:model/Bookshelf} The populated <code>Bookshelf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'BookshelfInner');
    }
    return obj;
  }

  Object.setPrototypeOf(exports.prototype, new Array());
  return exports;

}));
