/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Review'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Review'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.Reviews = factory(root.BookBlogApi.ApiClient, root.BookBlogApi.Review);
  }
}(this, function(ApiClient, Review) {
  'use strict';

  /**
   * The Reviews model module.
   * @module model/Reviews
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>Reviews</code>.
   * @alias module:model/Reviews
   * @class
   * @extends Array
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Reviews</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reviews} obj Optional instance to populate.
   * @return {module:model/Reviews} The populated <code>Reviews</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'Review');
    }
    return obj;
  }

  Object.setPrototypeOf(exports.prototype, new Array());
  return exports;

}));
