/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 0.0.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Book', 'model/Books'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Book'), require('../model/Books'));
  } else {
    // Browser globals (root is window)
    if (!root.BookBlogApi) {
      root.BookBlogApi = {};
    }
    root.BookBlogApi.BookApi = factory(root.BookBlogApi.ApiClient, root.BookBlogApi.Book, root.BookBlogApi.Books);
  }
}(this, function(ApiClient, Book, Books) {
  'use strict';

  /**
   * Book service.
   * @module api/BookApi
   * @version 0.0.4
   */

  /**
   * Constructs a new BookApi. 
   * @alias module:api/BookApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createBook operation.
     * @callback module:api/BookApi~createBookCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a book
     * @param {module:model/Book} book Info of book.
     * @param {module:api/BookApi~createBookCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.createBook = function(book, callback) {
      var postBody = book;

      // verify the required parameter 'book' is set
      if (book === undefined || book === null) {
        throw new Error("Missing the required parameter 'book' when calling createBook");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/books', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteBook operation.
     * @callback module:api/BookApi~deleteBookCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a book
     * Delete a 'book' object.
     * @param {Number} bookId Book's ID
     * @param {module:api/BookApi~deleteBookCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteBook = function(bookId, callback) {
      var postBody = null;

      // verify the required parameter 'bookId' is set
      if (bookId === undefined || bookId === null) {
        throw new Error("Missing the required parameter 'bookId' when calling deleteBook");
      }


      var pathParams = {
        'bookId': bookId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/books/{bookId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getBook operation.
     * @callback module:api/BookApi~getBookCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Book} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a book information
     * Gets `book` objects.
     * @param {Number} bookId Book's ID
     * @param {module:api/BookApi~getBookCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Book}
     */
    this.getBook = function(bookId, callback) {
      var postBody = null;

      // verify the required parameter 'bookId' is set
      if (bookId === undefined || bookId === null) {
        throw new Error("Missing the required parameter 'bookId' when calling getBook");
      }


      var pathParams = {
        'bookId': bookId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Book;

      return this.apiClient.callApi(
        '/books/{bookId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getBooks operation.
     * @callback module:api/BookApi~getBooksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Books} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all book
     * Returns a list containing all books. The list supports paging.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageNumber Page number
     * @param {module:api/BookApi~getBooksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Books}
     */
    this.getBooks = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'pageNumber': opts['pageNumber'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Books;

      return this.apiClient.callApi(
        '/books', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateBook operation.
     * @callback module:api/BookApi~updateBookCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a book info.
     * Update a 'book' object.
     * @param {Number} bookId Book's ID
     * @param {module:model/Book} book Info of book.
     * @param {module:api/BookApi~updateBookCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateBook = function(bookId, book, callback) {
      var postBody = book;

      // verify the required parameter 'bookId' is set
      if (bookId === undefined || bookId === null) {
        throw new Error("Missing the required parameter 'bookId' when calling updateBook");
      }

      // verify the required parameter 'book' is set
      if (book === undefined || book === null) {
        throw new Error("Missing the required parameter 'book' when calling updateBook");
      }


      var pathParams = {
        'bookId': bookId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/books/{bookId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
