/*
 * Book Blog API
 * This is a blog about books.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BookBlogApi);
  }
}(this, function(expect, BookBlogApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BookshelfInner', function() {
      beforeEach(function() {
        instance = new BookBlogApi.BookshelfInner();
      });

      it('should create an instance of BookshelfInner', function() {
        // TODO: update the code to test BookshelfInner
        expect(instance).to.be.a(BookBlogApi.BookshelfInner);
      });

      it('should have the property bookName (base name: "bookName")', function() {
        // TODO: update the code to test the property bookName
        expect(instance).to.have.property('bookName');
        // expect(instance.bookName).to.be(expectedValueLiteral);
      });

    });
  });

}));
